id: "abc"
description: "rubix-bios"
nats_url: "nats://localhost:4222"
proxy_port: 4223
root_path: "/ros"
apps_path: "apps"
system_path: ""
git_token: ""
git_download_path: "/ros/apps/library"

services:
  - ufw
  - mosquito
