id: "bios"
description: "rubix-bios"
nats_url: "nats://localhost:4222"
proxy_port: 4222
root_path: "/ros"
apps_path: "apps"
system_path: ""
git_token: ""
git_download_path: "/ros/apps/library"

web_server:
  enable: true
  port: 5000

jet_stream:
  store_enable: true
  store_name: "bios"

services:
  - ufw
  - mosquito
